---
# tasks file for selinux

- name: "{{ role_name }}_install_dependancies"
  package:
    name:
      - audit-libs-devel
      - bison
      - bzip2-devel
      - dbus-devel
      - dbus-glib-devel
      - flex
      - flex-devel
      - flex-static
      - glib2-devel
      - libcap-devel
      - libcap-ng-devel
      - pam-devel
      - pcre-devel
      - python3-devel
      - python3-setools
      - swig
      - xmlto
      - redhat-rpm-config
    state: present

- name: "{{ role_name }}_pull_selinux_repo"
  git:
    repo: https://github.com/SELinuxProject/selinux.git
    dest: /tmp/selinux

- name: "{{ role_name }}_build_install_selinux_python"
  make:
    target:
      - install
      - install-pywrap
      - relabel
    chdir: /tmp/selinux
    params:
      LIBDIR: /usr/lib64
      SHLIBDIR: /lib64
